# Puerto y nombre de la app
spring.application.name=mgwebsite

server.port=8080


# MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/microgames
spring.datasource.username=root
spring.datasource.password=Jada2003

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
# Thymeleaf
spring.thymeleaf.cache=false

# Session timeout (30 minutos por defecto)
server.servlet.session.timeout=30m

#Control de fechas
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

